version: '3.8'
services:
  backend:
    container_name: backendadminservice
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - mynetwork

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - mynetwork
# first create a network with the name mynetwork
# run: docker network create mynetwork
networks:
  mynetwork:
    external: true